name: qualita
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  multi_dropdown: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/help/create_task.gif
    - assets/help/edit_task.gif
    - assets/help/filter_tasks.gif
    - assets/help/upsert_tag.gif
    - assets/help/switch_theme.gif
